### ISSUE TITLE
Guidance on running agent in Amplify deployment

### ISSUE THREAD

**Issue by johngribbin** [newrelic/newrelic-node-nextjs#88]
## Is your feature request related to a problem? Please describe.
I am struggling to get newrelic agent working for my NextJs app deployed via AWS Amplify. I believe the issue is because the app is never actually "started" with the following command - `NODE_OPTIONS='-r @newrelic/next' next start`

See here the build/deploy settings detailed in the `yaml` file in Amplify: 

```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            # - ./test-e2e.sh
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: frontend
```

I have tried some experiments: 
- setting a `NODE_OPTIONS` env variable in Amplify for my app with a value of `-r @newrelic/next` - but this does not work.
- a preBuild command `node -r @newrelic/next` added to the yaml file detailed - but this threw a "module not found error" and caused the build to fail. 
- Import the agent at top of `_document.tsx` file like so `require('@newrelic/next')` - again, does not seem to work. 

## Feature Description
Just some guidance on how to get newrelic to work in Amplify environment for Next.js site!

## Describe Alternatives
Not sure

## Additional context
I have verified that the agent is starting successfully when working locally. `NODE_OPTIONS='-r @newrelic/next' next start` does the trick! Both server side & client side monitoring is getting picked up in newrelic. The issue only exists when the site is deployed via Amplify. 

I also could not find any help via the newrelic forum.  

## Priority
Really Want

p.s. Thanks in advance for this project, it is a welcome addition to the nextjs community!
